### ISSUE TITLE
hair won't grow back

### ISSUE THREAD

**Issue by Uqualm** [N3X15/Watchdog#1]
I don't know why but my hair just won't grow back. Anyway to fix?

**Comment by N3X15** [comment]
Quit shaving

**Comment by DrCelt** [comment]
You were linked on the /ss13g/ here:
boards.4chan.org/vg/thread/99498020/space-station-13-general-ss13g#p99594685
>Guys please make an issue report here and tell him you're sorry for bullying him while he was at ss13. Don't ask him to come back, just say thanks for his work and wish him luck at his new job.

in case you wanted to know the context of sarca being an arse
